#cargo-features = ["edition2021"]

[package]
name = "arrange_millis"
version = "0.1.0"
# 0.1.0 - initial
authors = ["Yury Bikuzin <yury.bikuzin@gmail.com>"]
edition = "2021"

[dependencies]

[dev-dependencies]
pretty_env_logger = "0.5"
